### ISSUE TITLE
Pathologic (1) and Pathologic 2

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#10]
[Pathologic 2](https://www.pcgamingwiki.com/wiki/Pathologic_2)'s `<path-to-game>\data` is being detected as the `data` directory for [Pathologic 1](https://www.pcgamingwiki.com/wiki/Pathologic).

Pathologic 2's \<path-to-game\> (Steam): `...\steamapps\common\Pathologic` (notice the lack of a "2").

To back up Pathologic 1 would backup irrelevant Pathologic 2 data. [Pathologic 1 isn't available on Steam](https://store.steampowered.com/search/?term=pathologic), only [Pathologic Classic HD](https://www.pcgamingwiki.com/wiki/Pathologic_Classic_HD).

Ludusavi 0.11.0

**Comment by mtkennerly** [comment]
Thanks for reporting this. This is an interesting one:

* Ludusavi 0.11.0: Using the new install directory ranking heuristics, the `Pathologic` folder is seen as an exact match with the game name, so it gets priority (even though Pathologic 2 has a confirmed `installDir` of `Pathologic` in the manifest).
* Ludusavi 0.10.0: It just looked for the game name as the install folder if there's no explicit `installDir`.

This would be hard to solve generically. If we just started prioritizing a known `installDir` over a matching title, then the same issue could happen in the opposite direction with other games. I'll need to think about how to handle this.

**Comment by redactedscribe** [comment]
Sort of a similar issue for [Overwatch](https://www.pcgamingwiki.com/wiki/Overwatch) and [Overwatch 2](https://www.pcgamingwiki.com/wiki/Overwatch_2) (notice that they share the same conf paths). The former is no longer officially accessible (OW2 replaces OW1) and I don't think there's a way to play it even illegitimately (e.g. private servers). Perhaps blacklist the Overwatch (1) manifest to avoid both from appearing?

**Comment by mtkennerly** [comment]
Thanks for the heads-up. I've removed Overwatch from the manifest.

About the banner, I'm not sure, but I think it might be automatic from being in this category: https://www.pcgamingwiki.com/wiki/Category:Unplayable_games . I think those games should still be in the manifest, though, as long as they're not duplicated with any other/newer versions. Overwatch is a bit special in that the config paths are 100% identical.

**Comment by redactedscribe** [comment]
I think you're right about that. There's probably a number of games in that list that people still play through some means and would to be able to back up their data.

Thanks for the Overwatch fix!
