### ISSUE TITLE
Game includes a directory not defined by its PCGW configuration path

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#12]
[A game](https://www.pcgamingwiki.com/wiki/Octopath_Traveler) in my Ludusavi games list appears to be showing a path that isn't defined by the "Configuration file(s) location" on PCGW.

PCGW shows the configuration location as "...\Config\WindowsNoEditor\\" but in the screenshot below, "Config" is showing two directories beneath it: the "WindowsNoEditor" and "CrashReportClient" directories.

![ludusavipath](https://user-images.githubusercontent.com/25013746/194749646-cdd910ea-09bb-435e-b597-feff95b5dc97.png)

Shouldn't it look like this instead?

![ludusavipath2](https://user-images.githubusercontent.com/25013746/194749794-314e975a-0ef0-4151-9608-1083a83a55a5.png)

The second screenshot is from a different game. The only difference (other than the game name, etc) between the two configuration location paths as shown on PCGW is that the former begins with "%USERPROFILE%\\...\\" and ends with a backslash and the latter with begins with "%LOCALAPPDATA%\\..." and has no ending backslash. But I'm guessing problem lies somewhere else though.

Windows 11
Ludusavi 0.13.1

**Comment by mtkennerly** [comment]
Hi! This is because of PCGW's save data entry for the game: `%USERPROFILE%\Documents\My Games\Octopath_Traveler\`. Since it's a parent folder of the config location, the config entry doesn't really matter. You could fix it by narrowing down the save location on PCGW.

**Comment by redactedscribe** [comment]
Oh, right. I think the save data path has been left to be less specific because the actual path is "...\Octopath_Traveler\<17-probably-random-numbers>\SaveGames". I don't know if PCGW has a way of handling that random string so perhaps the path is as specific as it can be.

**Comment by mtkennerly** [comment]
You could do `%USERPROFILE%\Documents\My Games\Octopath_Traveler\*\SaveGames` and then add a note like `{ii} "*" corresponds to...`. There's precedent for pages containing globs, and that should constrain it enough.

**Comment by redactedscribe** [comment]
Thanks for the suggestion. It should fix the issue.

**Comment by redactedscribe** [comment]
@mtkennerly I noticed that some paths on PCGW use `...\<user-id>\...` (`{{p|uid}}`). After some searches, it looks like Ludusavi understands paths with `<user-id>` in it, and I'm pretty sure the <17_probably_random_numbers> I mentioned above is actually a UID. I'll use that instead of  `*` and a `{{ii}}` comment.
