### ISSUE TITLE
Handle config/data location paths with more than one asterisk

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#15]
[Godlike Burger](https://www.pcgamingwiki.com/wiki/Godlike_Burger): E.g. `%USERPROFILE%\AppData\LocalLow\Liquid Pug LLC\Godlike Burger\*\*.es3`.

This is an edit I made but it doesn't show up in Ludusavi, presumably because of the use of two  asterisks? I think this was before you forced a new manifest.yaml update.

In this game's case, the first `*` is for 'Steam', 'EGS', 'GOG', etc, and the second is just a wildcard to grab all ES3 files.

Not sure if I should define the path different on PCGW to "fix" the issue, but I assume others may also make similar path definitions on other games. Could more than one asterisks be handled by Ludusavi?

Thanks.

**Comment by mtkennerly** [comment]
It works if I manually create a file there:

```
$ cargo run -- backup --preview 'Godlike Burger'
Godlike Burger [0 B]:
  - C:/Users/mtken/AppData/LocalLow/Liquid Pug LLC/Godlike Burger/foo/bar.es3
```

Could you double check if your local manifest was updated to include your change?

**Comment by redactedscribe** [comment]
The manifest didn't contain the changes. Should have really checked that myself before opening an issue. Sorry about that! The files are detected as expected now.
