### ISSUE TITLE
globetter issue

### ISSUE THREAD

**Issue by arilou** [mtkennerly/ludusavi-manifest#20]
Hi sorry for opening the issue here, I did not find any other way to contact you regarding globetter crate
(To fix it you can go to your fork repo Settings page, under General tab, check the box next to "Issues")

Thank you for your globetter fork it has some really nice fixes, I was hoping you will be willing to merge in
some other patches you can find in other forks:
https://github.com/aplanas/glob/tree/symlinks
https://github.com/GabrielDertoni/glob

Thanks and sorry for putting this issue on the wrong repo

**Comment by mtkennerly** [comment]
Hi! No worries about asking here. I've just enabled issues in Globetter.

I see you've opened a PR, so I'd be happy to take a look :)
