### ISSUE TITLE
DOSBOX games: Blake Stone and Tomb Raider

### ISSUE THREAD

**Issue by ajburley** [mtkennerly/ludusavi-manifest#21]
Hi, first of all thanks for this great app. I'm using it on my Steam Deck to sync a number of Steam games that don't have Steam Cloud support. In most cases it works fine.

A couple of my games are not detected by Ludusavi. I'm trying to figure out why, and what needs to be edited on PCGW. They are both DOSBOX games so I guess that has something to do with it.

So first the game "Blake Stone: Aliens of Gold"
https://www.pcgamingwiki.com/wiki/Blake_Stone:_Aliens_of_Gold

The DOS save file location is listed as "\<path to game\>\SAVEGAM*.BS6" which seems correct to me. On my Steam Deck, the actual file is in "/home/deck/.local/share/Steam/steamapps/common/Blake Stone Aliens of Gold/Blake Stone - Aliens of Gold/SAVEGAM0.BS6"

The Windows path refers to the DOS one. The Steam Play path points to a "pfx" directory which contains all kinds of stuff, but from experience with other games, Luduvici didn't try to backup the whole directory anyway.

Another game I am struggling with is Tomb Raider
https://www.pcgamingwiki.com/wiki/Tomb_Raider_(1996)

It's a very similar story. The PCGW gives the DOS save location as "\<path to game\>\SAVEGAME.*". On my Steam Deck this is "/home/deck/.local/share/Steam/steamapps/common/Tomb Raider (I)/TOMBRAID/SAVEGAME.0" but again, Ludusavi couldn't detect that file.

Again, I'm not sure what to edit on PCGW in either case.

Thanks again!

**Comment by ajburley** [comment]
Hi @mtkennerly thanks a lot for responding!

For Blake Stone no, there is no other data than just that folder.

For Tomb Raider 1, there is a load of stuff there apart from the TOMBRAID folder: folders and files. I think here you can see the whole contents of the "Tomb Raider (I)" folder including the TOMBRAID subfolder: https://steamdb.info/depot/224961/

I have no idea if this folder structure is Steam-specific, I'm afraid, as I only own the Steam versions of these games. Also the Windows path entry for Tomb Raider indicates to me that there is a Windows edition of the game, but that Steam is running the DOS version rather than Windows.

Which PCGW section does Ludusavi look at when the game is running on Linux via Steam Play (Proton)? Is it looking at DOS, Windows or Steam Play sections? I was still not clear on this.

**Comment by mtkennerly** [comment]
It actually looks at all of the sections to some degree. For example:

* If there's a DOS path relative to where the game is installed, it'll try to look up the same path on Linux, since it *may* be applicable on any OS but only documented on the wiki for one OS
* If there's a Windows path relative to some Windows-specific folder like AppData, it'll try to look up the path inside of the Proton prefix/compatdata folder for the game

**Comment by ajburley** [comment]
Checked again and those games are showing up now in Ludusavi, thanks!
