### ISSUE TITLE
Lego games: ludusavi uses pcgamingwiki's "Configuration file(s) location" path instead of "Save game data location"

### ISSUE THREAD

**Issue by RiseT** [mtkennerly/ludusavi-manifest#23]
As an example, I'm using Lego DC Super-Villains here:
https://www.pcgamingwiki.com/wiki/Lego_DC_Super-Villains

As per pcgamingwiki ("Save game data location"), the actual save game data (MS Windows) is stored at
%APPDATA%\Warner Bros. Interactive Entertainment\LEGO DC Super-villains\SAVEDGAMES\

But ludusavi backs up the parent folder:
%APPDATA%\Warner Bros. Interactive Entertainment\LEGO DC Super-villains\

which, aside from the folder "SAVEDGAMES", also contains the folders "CACHEDSHADERS", "CRASHDATA" and the file "PCCONFIG.TXT" (this contains the game's configuration).

That parent folder's path is indeed mentioned in pcgamingwiki, but under the title "Configuration file(s) location" (as "PCCONFIG.TXT" is stored there).

So essentially, ludusavi seems to use pcgamingwiki's "Configuration file(s) location" path, and not its "Save game data location" path (which of course includes the game saves as well).

Just wondering why this is the case, as useless data like "CACHEDSHADERS" gets backed up as well that way.

**Comment by mtkennerly** [comment]
> So essentially, ludusavi seems to use pcgamingwiki's "Configuration file(s) location" path, and not its "Save game data location" path (which of course includes the game saves as well).

It uses both; it's just not obvious since the config path is a superset of the save path. My thinking was that it's better to back up too much than too little, especially since you can uncheck any files/folders you're not interested in.

That said, it would probably be worth adding an option to skip the config paths altogether.

**Comment by RiseT** [comment]
> That said, it would probably be worth adding an option to skip the config paths altogether.

Yes, in fact I was looking for such an option.
