### ISSUE TITLE
What role does the ‘tags’ field play in the entire workflow?

### ISSUE THREAD

**Issue by rosystain** [mtkennerly/ludusavi-manifest#27]
When creating a secondary manifest, I encountered some confusion. I don't understand how the "tags" field functions in a yaml file, and what kind of tag should I assign to a directory.

Generally, I would set the tag for the main save directory of a game as "save". But I am not sure that if I need to assign specific tags like "config" to directories that store screenshots or settings.

Since even if I set all directories as "save," they still function properly. I'm curious about the differences between different tags.

**Comment by mtkennerly** [comment]
Right now, Ludusavi itself doesn't use the tags for anything, but in the future, it may have an option to skip paths with certain tags and show the relevant tags next to each file. The `save` and `config` tags are mapped from PCGamingWiki's `Save game data location` and `Configuration file(s) location` sections respectively.

For a directory, if it contains both saves and config, then you can tag it with both. But if you don't care about that potential future feature, then you don't have to specify any tags.

**Comment by rosystain** [comment]
Thank you, I understand.
