### ISSUE TITLE
Fallout 3 GOTY is missing from Manifest 

### ISSUE THREAD

**Issue by marciocr** [mtkennerly/ludusavi-manifest#28]
The GOTY version is treated by Steam as a separate game (the regular version has the ID: 22300 and the GOTY version is 22370 ) but in PCGamingWiki it is treated as if it were a DLC.

Would it be possible to add ID 22370 to the manifest?

**Comment by mtkennerly** [comment]
Hi! The manifest includes 22370 under `Fallout 3` > `id` > `steamExtra`. The next release of Ludusavi will make use of that field to handle cases like this :)
