### ISSUE TITLE
Dinkum Windows save data location not being detected

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#30]
I'm not sure if this is a wider problem, but [Dinkum](https://www.pcgamingwiki.com/wiki/Dinkum)'s save data (`%USERPROFILE%\AppData\LocalLow\James Bendon\Dinkum`) isn't being detected by Ludusavi, only its config (registry path). 1 MiB of files and folders are present at the save data path, yet Ludusavi still shows "0 B" next to Dinkum in the Backup Mode list. Why would this be the case? Backing up Dinkum backs up the config correctly, just no save data.

![ludusavi_2023-08-10_23-12-28](https://github.com/mtkennerly/ludusavi-manifest/assets/25013746/68724a45-d05c-450c-9234-5e6107287d48)

Thanks!

**Comment by mtkennerly** [comment]
Thanks for reporting this! It was because of the `<ref>` tag on PCGW:

```
{{Game data/saves|Windows|{{p|userprofile\appdata\locallow}}\James Bendon\Dinkum<ref>{{Refurl|url=https://dinkum.fandom.com/wiki/Saved_Games|title=dinkum.fandom.com|date=9 June 2023}}</ref>}}
```

This affected a few other games too. Fixed in 261dfdc37874918ef483abd9ec3f557963ff49e8.
