### ISSUE TITLE
`<base>` not detected for game in a root

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#34]
[Death Stranding Director's Cut on PCGW](https://www.pcgamingwiki.com/wiki/Death_Stranding_Director%27s_Cut) (Epic) defines the config file location as `<path-to-game>\settings.cfg`. In Ludusavi, this is defined as `<base>/settings.cfg`. The issue is that previewing Death Stranding Director's Cut in Ludusavi won't locate the `settings.cfg` file and I'm not sure why. The game is detected so it's in a defined root, but why can't Ludusavi determine its installation directory correctly and find the config file?

- Creating a custom game entry for the game and swapping `<base>` for the exact location of `settings.cfg` detects the file just fine.
- Perhaps there is a conflict somehow as I have the non-Director's Cut version's `settings.cfg` still present on my system (or rather, in a backup and therefore Ludusavi shows it as missing)?

![ludusavi_2023-12-16_17-42-43](https://github.com/mtkennerly/ludusavi-manifest/assets/25013746/a2007e0b-3579-4476-9e3c-0d9010aa1cbc)

(The folded folders also do not contain `settings.cfg`.)

Thanks.

**Comment by redactedscribe** [comment]
> Perhaps there is a conflict somehow as I have the non-Director's Cut version's `settings.cfg` still present on my system (or rather, in a backup and therefore Ludusavi shows it as missing)?

Temporarily deleting my backup only removed the `settings.cfg` from showing on the standard Death Stranding. It did not show up on the Director's Cut version.

**Comment by mtkennerly** [comment]
Hi! `DeathStrandingDC` wasn't a known install directory in the manifest, and it wasn't close enough to the game title for Ludusavi to infer it.

I've added an override entry, so this should be fixed when you download the updated manifest :)

**Comment by redactedscribe** [comment]
Thanks as always @mtkennerly! I'll reopen this in the unlikely event the fix didn't work.
