### ISSUE TITLE
Add delta update capabilities

### ISSUE THREAD

**Issue by mainrs** [mtkennerly/ludusavi-manifest#37]
Most of the update commits are super small. They contain few changes.

As of now, it is necessary to download the whole manifest every time an update is available. 

I "propose" some kind of delta update functionality: The current file becomes the active "base file". And for a certain amount of time, lets say two weeks, every change to the wiki is published as a delta file. And these files can be applied in-order to get to the newest version of the manifest. These files only contain the information that changed instead of the whole manifest. And there entries are always superseeding existing entries in the manifest.

Compared to now: for users that have the newest file this will be a super small download. For users that need the manifest for the first time this will be a larger download. But they will save bandwidth over time. I went through the last commits and the data that changes was around 300 bytes every update commit.

And to not have to download that many patches, after a certain time frame, the base file gets updated by applying all existing patches to it.

**Comment by mtkennerly** [comment]
Thanks for the suggestion! I agree that the reduced bandwidth would be nice, but there are also some mitigating factors that I think make the current situation acceptable:

* Ludusavi requests that GitHub send a gzip-compressed copy of the file, which is then decompressed locally. Testing with Curl, that would cut the download size from 12.5 MB to 1.7 MB (14% of original size).
* Unless you force a refresh sooner, Ludusavi will only check for an update after at least 24 hours. If you use Ludusavi every day, that's around 12 MB per week with gzip compression.

That's at a low enough level where I think the trade-off for simplicity is worth it.

**Comment by mainrs** [comment]
Ah ,you are right. I totally forgot about Gzip. 1.7MB is totally acceptable :) Thanks for the detailed answer!
