### ISSUE TITLE
The  path of Civilization 6 purchased by epic is different from that of steam

### ISSUE THREAD

**Issue by mayziran** [mtkennerly/ludusavi-manifest#39]
at Documents\My Games\Sid Meier's Civilization VI (Epic)

**Comment by sharkusmanch** [comment]
The manifest pulls save data from PCGamingWiki daily. Can always update there if you find something missing.

I've updated the Civ VI page to include this new info - https://www.pcgamingwiki.com/wiki/Sid_Meier%27s_Civilization_VI#Save_game_data_location

Will be included in tomorrow's update

**Comment by mtkennerly** [comment]
Thanks, @sharkusmanch!
