### ISSUE TITLE
Binding of isaac : Rebirth

### ISSUE THREAD

**Issue by lilezek** [mtkennerly/ludusavi-manifest#42]
From GOG, the save path I have is

```
<winDocument>/My Games/Binding of Isaac Repentance (Galaxy)
```

which is missing in the manifest.

**Comment by mtkennerly** [comment]
Hi! In cases like this, you can add the missing paths on PCGamingWiki, and Ludusavi will automatically pick it up. I've [updated the article](https://www.pcgamingwiki.com/w/index.php?title=The_Binding_of_Isaac:_Rebirth&diff=1488883&oldid=1486346) for this game, so you'll see it recognized in Ludusavi soon :)
