### ISSUE TITLE
Incorrectly parsing `''(Note text)''` in paths

### ISSUE THREAD

**Issue by RuiNtD** [mtkennerly/ludusavi-manifest#43]
From [PCGamingWiki:Editing guide/Game data]:
> If it is felt to be needed to add notes on specific game versions, this can be done after the filepath with {{note|Note text}} or ''(Note text)''.

Ludusavi's manifest should be ignoring the `''` notes, but it is instead interpreting them as part of the path. This is used on the [Minecraft: Bedrock Edition] page to indicate paths for Minecraft Preview.

[PCGamingWiki:Editing guide/Game data]: https://www.pcgamingwiki.com/wiki/PCGamingWiki:Editing_guide/Game_data
[Minecraft: Bedrock Edition]: https://www.pcgamingwiki.com/wiki/Minecraft:_Bedrock_Edition

**Comment by mtkennerly** [comment]
Thanks for the report! I just fixed this.
