### ISSUE TITLE
Add support for Ryujinx

### ISSUE THREAD

**Issue by felipecrs** [mtkennerly/ludusavi-manifest#44]
It would be great to have support for Ryujinx now that Yuzu is dead.

**Comment by mtkennerly** [comment]
Hi!

I was going to say that the manifest doesn't cover emulators, but apparently some of them are included. It looks like several of the [emulator articles](https://www.pcgamingwiki.com/wiki/Category:Emulators) on PCGamingWiki used to be in the [games category](https://www.pcgamingwiki.com/wiki/Category:Games), and although they're not in that category anymore, the manifest import script didn't check whether the category changed.

Let me think a bit about how to handle this.

**Comment by felipecrs** [comment]
I see. Despite this fact, don't you think it would be tremendously useful being able to backup save games from emulators in general?

As per custom game, yeah, I'm aware of it, thank you. I just thought of why not letting everyone else benefit from such ready to use configuration.

**Comment by mtkennerly** [comment]
Yeah, that's fair. I've added it to the manifest :)

**Comment by felipecrs** [comment]
That's really nice. I super appreciate it, and hope more people will do too. I also noticed a few more emulators now. Extra cool!
