### ISSUE TITLE
Immortals Fenyx Rising missing save data in manifest

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi-manifest#45]
Game name: `Immortals Fenyx Rising`

https://www.pcgamingwiki.com/wiki/Immortals_Fenyx_Rising

Manifest data:
```
Immortals Fenyx Rising:
  installDir:
    Immortals Fenyx Rising: {}
  launch:
    "<base>/ImmortalsFenyxRising.exe":
      - arguments: "-uplay_steam_mode"
        when:
          - store: steam
  steam:
    id: 2221920
```

**Comment by sharkusmanch** [comment]
Is this a parsing error?

If so would it be worthwhile to maintain a list of wiki game articles that have errors parsing? Would make it easier for the community to correct

**Comment by mtkennerly** [comment]
> Is this a parsing error?

Yep, good guess!

```
  Error: the file ended, but we expected more content at line 462, column 15
  Error: found an unmatched double open brace {{ at line 462, column 15
```

> If so would it be worthwhile to maintain a list of wiki game articles that have errors parsing? Would make it easier for the community to correct

I'm open to that. We already track that info in wiki-game-cache.yaml (`malformed: true`), so it's easy enough to add: https://github.com/mtkennerly/ludusavi-manifest/blob/master/data/wiki-malformed.md

**Comment by mtkennerly** [comment]
Also, it can be really hard to track down where the bad syntax is, so I just added a command for testing:

```
cargo run -- wikitext
```

By default, it'll read `{repo}/tmp/wiki.txt`, but you can pass in another path. So you can copy/paste the article into the file, then start deleting sections until the parsing errors go away, so at least then you know which section has the error 😅

**Comment by mtkennerly** [comment]
This was the issue: https://www.pcgamingwiki.com/w/index.php?title=Immortals_Fenyx_Rising&diff=1497087&oldid=1490921

**Comment by sharkusmanch** [comment]
Awesome. Thanks for the quick resolution!
