### ISSUE TITLE
cannot parse `manifest.yml` with `yq`

### ISSUE THREAD

**Issue by aanderse** [mtkennerly/ludusavi-manifest#49]
i can't seem to parse [manifest.yaml](https://github.com/mtkennerly/ludusavi-manifest/blob/f78ccec5b1c24444b6cbed5790ef1236bdd0ef53/data/manifest.yaml) with `yq` because an invalid character

i have tried several different `python` libraries and all fail to parse the file

any hints?

```shell
$ yq '.' manifest.yaml
yq: Error running jq: ReaderError: unacceptable character #x0081: control characters are not allowed
  in "manifest.yaml", position 1452746.
```

any and all help appreciated :bowing_man:

**Comment by mtkennerly** [comment]
Hi! It looks like serde_yaml 0.8.26 doesn't properly escape control characters in strings. I'm avoiding upgrading that dependency for now, so I've added a filter for those characters instead. `yq` seems to be happy now :)

**Comment by aanderse** [comment]
great! thank you very much! ❤️
