### ISSUE TITLE
[Question] Licensing of PCGW data

### ISSUE THREAD

**Issue by largestgithubuseronearth** [mtkennerly/ludusavi-manifest#54]
Hello,

I'm in the early stages of making a game backup app for Linux but it seems you've already beat me to this idea. Congrats. I'd like to use your manifest data for my app but I'm concerned about licensing compatibilities between my project, yours, and PCGW. 

How would the **Share-Alike** clause from PCGW's [CC BY-NC-SA 3.0 license](https://creativecommons.org/licenses/by-nc-sa/3.0/) apply to a tool downloading that data from a separate source? Do I need to license my app under the same CC license? How do you get around the SA clause to license your project under MIT when it's distributing the same data? Do you have permission from PCGW?

I couldn't find a clear answer on the PCGW or CC website for this case but I figure you might know since you have your own backup tool based on this.

Thanks

**Comment by mtkennerly** [comment]
Hi! You're welcome to use the manifest for your project :)

I'm not a lawyer, but to the best of my understanding, copyright applies to creative work, not to factual information. The save paths themselves are strictly factual and non-creative, so there's no copyright protection on the data itself. That's reinforced here: https://creativecommons.org/faq/#do-creative-commons-licenses-affect-exceptions-and-limitations-to-copyright-such-as-fair-dealing-and-fair-use

**Comment by largestgithubuseronearth** [comment]
Okay, it seems you're right. Sui generis database rights are preserved by CC as they mention in their [section on data](https://wiki.creativecommons.org/wiki/data) but those rights aren't respected in American copyright law.

I'm satisfied then. Thanks for clearing things up :)
