### ISSUE TITLE
Marvel's Spider-Man Remastered

### ISSUE THREAD

**Issue by MichaelMKenny** [mtkennerly/ludusavi-manifest#9]
The game is listed in the manifest, but there's no save directory in there. PCGamingWiki already has a save directory listed on the its page.

**Comment by mtkennerly** [comment]
It looks like the save location was added to the wiki in the last 24 hours, so it just hadn't been picked up by the daily update yet. I ran a manual update, so it's there now :)

**Comment by MichaelMKenny** [comment]
Thank you. Much appreciated :)
